import type { DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, Module, PartialLangiumServices } from 'langium';
import { createDefaultModule, createDefaultSharedModule, inject } from 'langium';
import { MosaicGeneratedModule, MosaicGeneratedSharedModule } from './generated/module.js';
import { MosaicValidator, registerValidationChecks } from './mosaic-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type MosaicAddedServices = {
    validation: {
        MosaicValidator: MosaicValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type MosaicServices = LangiumServices & MosaicAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const MosaicModule: Module<MosaicServices, PartialLangiumServices & MosaicAddedServices> = {
    validation: {
        MosaicValidator: () => new MosaicValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createMosaicServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Mosaic: MosaicServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        MosaicGeneratedSharedModule
    );
    const Mosaic = inject(
        createDefaultModule({ shared }),
        MosaicGeneratedModule,
        MosaicModule
    );
    shared.ServiceRegistry.register(Mosaic);
    registerValidationChecks(Mosaic);
    return { shared, Mosaic };
}
