version: '3.9'
services:
  extract_gitlab:
    container_name: mosaic_discord
    build: .
    environment:
      - WEBHOOK=${WEBHOOK}
      - FOLDER=${FOLDER}
    volumes:
      - ./meetings:/app/meetings/
    env_file:
    - .env